# Generated by Django 2.1.7 on 2019-04-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_auto_20190402_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.ImageField(default='images/no_image.png', upload_to='images/producers'),
        ),
    ]
