# Generated by Django 2.1.7 on 2019-03-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='../static/images/no_image.png', upload_to='static/images/movies'),
        ),
    ]
